### ISSUE TITLE
Plugin error encountered when trying to create a Snowflake sink connector

### ISSUE THREAD

**Issue by andreniklasson** [confluentinc/terraform-provider-confluent#119]
Hello there!

I have been trying to create a Snowflake Sink connector using this terraform provider v1.8.0 but I'm stuck with this error: 
```
╷
│ Error: Plugin did not respond
│ 
│   with confluent_connector.snowflake,
│   on snowflake.tf line 1, in resource "confluent_connector" "snowflake":
│    1: resource "confluent_connector" "snowflake" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-confluent_1.8.0 plugin:

panic: reflect: call of reflect.Value.FieldByName on ptr Value

goroutine 15 [running]:
reflect.flag.mustBe(...)
	/home/semaphore/.goenv/versions/1.18.0/src/reflect/value.go:223
reflect.Value.FieldByName({0x19e2a40?, 0xc0005062d8?, 0xc0002c6800?}, {0x1b69c5e?, 0xc0001229b8?})
	/home/semaphore/.goenv/versions/1.18.0/src/reflect/value.go:1297 +0x1d6
github.com/confluentinc/terraform-provider-confluent/internal/provider.createDescriptiveError({0x1ceee40, 0xc0002c6800})
	src/github.com/confluentinc/terraform-provider-confluent/internal/provider/utils.go:347 +0x2be
github.com/confluentinc/terraform-provider-confluent/internal/provider.connectorCreate({0x1cf2f50, 0xc00010d440}, 0xc00011fc00, {0x1b0b500?, 0xc0001dd860?})
	src/github.com/confluentinc/terraform-provider-confluent/internal/provider/resource_connector.go:145 +0xa54
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000154fc0, {0x1cf2f88, 0xc0003a1410}, 0xd?, {0x1b0b500, 0xc0001dd860})
	pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000154fc0, {0x1cf2f88, 0xc0003a1410}, 0xc0005b71e0, 0xc00011fa80, {0x1b0b500, 0xc0001dd860})
	pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003051e8, {0x1cf2ee0?, 0xc00011aa40?}, 0xc00009b770)
	pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00024c320, {0x1cf2f88?, 0xc0003a0c30?}, 0xc000472230)
	pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1b2b720?, 0xc00024c320}, {0x1cf2f88, 0xc0003a0c30}, 0xc00010cd20, 0x0)
	pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001348c0, {0x1cf5d50, 0xc0002ea820}, 0xc0003d86c0, 0xc00010f0b0, 0x232aac0, 0x0)
	pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0001348c0, {0x1cf5d50, 0xc0002ea820}, 0xc0003d86c0, 0x0)
	pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-confluent_1.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

My confluent_connector resource looks like this:
```
resource "confluent_connector" "snowflake" {
  environment {
    id = var.kafka_cluster.environment_id
  }
  kafka_cluster {
    id = var.kafka_cluster.id
  }

  config_sensitive = {
    "snowflake.private.key" = "${var.snowflake_private_key}"
    "snowflake.private.key.passphrase" = "${var.snowflake_passphrase}"
  } 

  config_nonsensitive = {
    "connector.class"         = "SnowflakeSink"
    "input.data.format"       = "JSON"
    "name"                    = "SnowflakeSinkConnector_0"
    "kafka.auth.mode"         = "SERVICE_ACCOUNT"
    "kafka.service.account.id"  = "${confluent_service_account.service.id}"
    "tasks.max"               = "2" 
    "snowflake.database.name" = "CONFLUENT_CLOUD_KAFKA"
    "snowflake.schema.name"   = "KAFKA" 
    "snowflake.url.name"      = <SNOWFLAKE_URL>
    "snowflake.user.name"     = "CONFLUENT_USER" 
    "topics"                  = "topic_name"
  }
}
```

Would be grateful for help!

**Comment by linouk23** [comment]
@andreniklasson thanks for creating this issue!

I'll take a look at it early next week but -- in case your request is super urgent, I can tell that there's something wrong with input and you might want to use [this method](https://docs.confluent.io/cloud/current/api.html#tag/Plugins-(v1)/operation/validateConnectv1ConnectorPlugin) to validate your input manually.

**Comment by suraj2410** [comment]
I got similar error while creating ACL
more details in https://github.com/confluentinc/terraform-provider-confluent/issues/120

**Comment by nick-osborn** [comment]
+1
Getting exact same error for MQTT source connector as of 1.8.0. My last connector with almost identical config on 1.6.0 created with no issues. Other source MQTT connectors with no changes had no issue, so it doesnt appear to be introducing anything breaking for existing connectors.

module.mqtt_source_response.confluent_connector.mqtt_source: Creating...
╷
│ Error: Request cancelled
│ 
│   with module.mqtt_source_response.confluent_connector.mqtt_source,
│   on .terraform/modules/mqtt_source_response/modules/connectors/mqtt/source/mqtt_source.tf line 10, in resource "confluent_connector" "mqtt_source":
│   10: resource "confluent_connector" "mqtt_source" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-confluent_1.8.0 plugin:

panic: reflect: call of reflect.Value.FieldByName on ptr Value

goroutine 105 [running]:
reflect.flag.mustBe(...)
        /home/semaphore/.goenv/versions/1.18.0/src/reflect/value.go:223
reflect.Value.FieldByName({0xde3cc0?, 0xc000116968?, 0xc0002d6f80?}, {0xf6a24e?, 0xc000437228?})
        /home/semaphore/.goenv/versions/1.18.0/src/reflect/value.go:1297 +0x1d6
github.com/confluentinc/terraform-provider-confluent/internal/provider.createDescriptiveError({0x10efa00, 0xc0002d6f80})
        src/github.com/confluentinc/terraform-provider-confluent/internal/provider/utils.go:347 +0x2be
github.com/confluentinc/terraform-provider-confluent/internal/provider.connectorCreate({0x10f3b10, 0xc000792ea0}, 0xc00068b700, {0xf0bb00?, 0xc0002cfa00?})
        src/github.com/confluentinc/terraform-provider-confluent/internal/provider/resource_connector.go:145 +0xa54
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0006290a0, {0x10f3b48, 0xc0006b20f0}, 0xd?, {0xf0bb00, 0xc0002cfa00})
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0006290a0, {0x10f3b48, 0xc0006b20f0}, 0xc0005d01a0, 0xc00068b580, {0xf0bb00, 0xc0002cfa00})
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000602828, {0x10f3aa0?, 0xc0003c7c00?}, 0xc0000cba40)
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000238fa0, {0x10f3b48?, 0xc0002c95f0?}, 0xc000451490)
        pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xf2bac0?, 0xc000238fa0}, {0x10f3b48, 0xc0002c95f0}, 0xc000792600, 0x0)
        pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ecc40, {0x10f6890, 0xc0001036c0}, 0xc0005dc240, 0xc0002346f0, 0x1727b40, 0x0)
        pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002ecc40, {0x10f6890, 0xc0001036c0}, 0xc0005dc240, 0x0)
        pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-confluent_1.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

My module looks like this:
module mqtt_source_response {
depends_on = [module.dpe_mqtt_response_topic_build]
source = "git::<redacted_repo>//modules/connectors/mqtt/source?ref=develop"

name = "mqtt_response"
env = var.env
#mqtt-specific
mqtt_server_uri = "redacted_uri"
topics = "aws/things/+/prod/cmd/response"
qos = "0"
kafka_topic = "${var.env}_response"
#Auth
mqtt_ssl_keystore_file = var.kv2_cs_keystore
mqtt_ssl_keystore_password = var.kv2_cs_keystore_pass
mqtt_ssl_key_password = var.kv2_cs_key_pass
}

**Comment by nick-osborn** [comment]
Downgrade to 1.7.0 gives the same, going to try again with 1.6.0 downgrade


│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-confluent_1.7.0 plugin:

panic: reflect: call of reflect.Value.FieldByName on ptr Value

goroutine 48 [running]:
reflect.flag.mustBe(...)
        /home/semaphore/.goenv/versions/1.18.0/src/reflect/value.go:223
reflect.Value.FieldByName({0xdc5d80?, 0xc00037e0b8?, 0xc00079e100?}, {0xf46e8e?, 0xc000448878?})
        /home/semaphore/.goenv/versions/1.18.0/src/reflect/value.go:1297 +0x1d6
github.com/confluentinc/terraform-provider-confluent/internal/provider.createDescriptiveError({0x10c8880, 0xc00079e100})
        src/github.com/confluentinc/terraform-provider-confluent/internal/provider/utils.go:334 +0x2be
github.com/confluentinc/terraform-provider-confluent/internal/provider.connectorCreate({0x10cc970, 0xc00050d020}, 0xc0007d1880, {0xee17c0?, 0xc0002c2840?})
        src/github.com/confluentinc/terraform-provider-confluent/internal/provider/resource_connector.go:145 +0xa54
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00052a9a0, {0x10cc9a8, 0xc0007cb6b0}, 0xd?, {0xee17c0, 0xc0002c2840})
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00052a9a0, {0x10cc9a8, 0xc0007cb6b0}, 0xc0007a55f0, 0xc0007d1700, {0xee17c0, 0xc0002c2840})
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000df38, {0x10cc900?, 0xc0001143c0?}, 0xc000792fa0)
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000238960, {0x10cc9a8?, 0xc0007caea0?}, 0xc00058c070)
        pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xf09640?, 0xc000238960}, {0x10cc9a8, 0xc0007caea0}, 0xc00050c6c0, 0x0)
        pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002e8700, {0x10cf6f0, 0xc000582ea0}, 0xc0007bbe60, 0xc000538c00, 0x16ec980, 0x0)
        pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002e8700, {0x10cf6f0, 0xc000582ea0}, 0xc0007bbe60, 0x0)
        pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-confluent_1.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by linouk23** [comment]
@nick-osborn thanks for reporting!

Could you try to use [this method](https://docs.confluent.io/cloud/current/api.html#tag/Plugins-(v1)/operation/validateConnectv1ConnectorPlugin) to validate your input manually?

**Comment by nick-osborn** [comment]
:) Was finishing the downgrade test to 1.6 and then realized it... it was the same name as my other connector. Ill check that out next time though, didnt realize that api was available.

Its playing nice on 1.8.0 now for that issue. Its failing on something different thats a "my problem" thing. Most likely source perms for the mqtt topic.

Might be a nice feature to throw in a complaint from provider that you cant have 2 connectors with the same name for future release.

**Comment by nick-osborn** [comment]
@andreniklasson, I have some running snowflake connector modules as well. As near as I can tell without the redacted urls and such your config look correct to me except that it looks like its missing the broker details. I assumed that was required on all of connectors.

    "confluent.topic.bootstrap.servers" = "broker:29092"
    "confluent.topic.replication.factor" = "1"
    "confluent.license" = ""
    
    If it helps, here's the full module config. The only other difference I see is that I dont have a passkey for my private key. 
    I pass most everything with vars so it can be more configurable for multiple use cases.
    
    resource "confluent_connector" "snowflake_sink" {
  environment {
    id = data.confluent_environment.env.id
  }
  kafka_cluster {
    id = data.confluent_kafka_cluster.cluster.id
  }

  config_sensitive = {"snowflake.private.key" = var.snowflake_privatekey}

  config_nonsensitive = {
    "input.data.format"        = var.input_data_format
    "connector.class"          = var.connector_class
    "name"                     = "${var.env}_${substr(var.name,0,58)}_${var.service}"     
    "kafka.auth.mode"          = var.kafka_auth_mode
    "kafka.service.account.id" = data.confluent_service_account.confluent_cluster_sa.id
    "tasks.max"                = var.tasks_max  
    "topics"                   = var.topics
    "confluent.topic.bootstrap.servers" = "broker:29092"
    "confluent.topic.replication.factor" = "1"
    "confluent.license" = ""
    #snowflake specific
    "snowflake.url.name" = lookup(var.snowflake_url_name, var.env)
    "snowflake.user.name" = var.snowflake_username
    "snowflake.database.name" = var.snowflake_database_name
    "snowflake.schema.name" = var.snowflake_schema_name
    # "snowflake.topic2table.map" = 
  }
}

**Comment by linouk23** [comment]
I'm happy to hear you managed to resolve your issue!

> Might be a nice feature to throw in a complaint from provider that you cant have 2 connectors with the same name for future release.

That's likely what API returns and TF Provider should be able to show the same error but I wanted to double check it.

**Comment by nick-osborn** [comment]
As always, very much appreciate the prompt responses. Im starting to wonder if you ever sleep. ;) Or maybe youre a really well-constructed Confluent AI chatbot.

**Comment by linouk23** [comment]
As @nick-osborn said before, the problem could be 

> :) Was finishing the downgrade test to 1.6 and then realized it... it was the same name as my other connector. Ill check that out next time though, didnt realize that api was available.

I managed to reproduce it by trying to connect 2 connectors with the same name:
```
resource "confluent_connector" "snowflake" {
  environment {
    id = "env-m25jqx"
  }
  kafka_cluster {
    id = "lkc-1n0xw3"
  }

  config_sensitive = {
    "snowflake.private.key" = "aaa"
    "snowflake.private.key.passphrase" = "bbb"
  }

  config_nonsensitive = {
    "connector.class"         = "SnowflakeSink"
    "input.data.format"       = "JSON"
    "name"                    = "SnowflakeSinkConnector_0"
    "kafka.auth.mode"         = "SERVICE_ACCOUNT"
    "kafka.service.account.id"  = confluent_service_account.app-manager.id
    "tasks.max"               = "2"
    "snowflake.database.name" = "CONFLUENT_CLOUD_KAFKA"
    "snowflake.schema.name"   = "KAFKA"
    "snowflake.url.name"      = "aaa.us-east-1.snowflakecomputing.com:443"
    "snowflake.user.name"     = "CONFLUENT_USER"
    "topics"                  = "topic_name"
  }

  depends_on = [
    confluent_role_binding.app-manager-kafka-cluster-admin
  ]
}

resource "confluent_connector" "snowflake_2" {
  environment {
    id = "env-m25jqx"
  }
  kafka_cluster {
    id = "lkc-n0xw3"
  }

  config_sensitive = {
    "snowflake.private.key" = "aaa"
    "snowflake.private.key.passphrase" = "bbb"
  }

  config_nonsensitive = {
    "connector.class"         = "SnowflakeSink"
    "input.data.format"       = "JSON"
    "name"                    = "SnowflakeSinkConnector_0"
    "kafka.auth.mode"         = "SERVICE_ACCOUNT"
    "kafka.service.account.id"  = confluent_service_account.app-manager.id
    "tasks.max"               = "2"
    "snowflake.database.name" = "CONFLUENT_CLOUD_KAFKA"
    "snowflake.schema.name"   = "KAFKA"
    "snowflake.url.name"      = "aaa.us-east-1.snowflakecomputing.com:443"
    "snowflake.user.name"     = "CONFLUENT_USER"
    "topics"                  = "topic_name"
  }

  depends_on = [
    confluent_role_binding.app-manager-kafka-cluster-admin
  ]
}
```

```
Plan: 2 to add, 0 to change, 0 to destroy.
confluent_connector.snowflake: Creating...
confluent_connector.snowflake_2: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with confluent_connector.snowflake,
│   on main.tf line 46, in resource "confluent_connector" "snowflake":
│   46: resource "confluent_connector" "snowflake" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: error creating Connector "SnowflakeSinkConnector_0": error sending validation request: 403 Forbidden
│ 
│   with confluent_connector.snowflake_2,
│   on main.tf line 78, in resource "confluent_connector" "snowflake_2":
│   78: resource "confluent_connector" "snowflake_2" {
│ 
╵

Stack trace from the terraform-provider-confluent_1.8.0 plugin:

panic: reflect: call of reflect.Value.FieldByName on ptr Value

goroutine 72 [running]:
reflect.flag.mustBe(...)
        /home/semaphore/.goenv/versions/1.18.0/src/reflect/value.go:223
reflect.Value.FieldByName({0x19e2a40?, 0xc00049ce98?, 0xc0002a5380?}, {0x1b69c5e?, 0xc000181278?})
        /home/semaphore/.goenv/versions/1.18.0/src/reflect/value.go:1297 +0x1d6
github.com/confluentinc/terraform-provider-confluent/internal/provider.createDescriptiveError({0x1ceee40, 0xc0002a5380})
        src/github.com/confluentinc/terraform-provider-confluent/internal/provider/utils.go:347 +0x2be
github.com/confluentinc/terraform-provider-confluent/internal/provider.connectorCreate({0x1cf2f50, 0xc00010e3c0}, 0xc000706500, {0x1b0b500?, 0xc0002b0c30?})
        src/github.com/confluentinc/terraform-provider-confluent/internal/provider/resource_connector.go:145 +0xa54
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0000f8fc0, {0x1cf2f88, 0xc0006dab10}, 0xd?, {0x1b0b500, 0xc0002b0c30})
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000f8fc0, {0x1cf2f88, 0xc0006dab10}, 0xc00064a270, 0xc000706380, {0x1b0b500, 0xc0002b0c30})
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00013d218, {0x1cf2ee0?, 0xc00036c340?}, 0xc0006b5450)
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000598fa0, {0x1cf2f88?, 0xc00036a030?}, 0xc000322000)
        pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1b2b720?, 0xc000598fa0}, {0x1cf2f88, 0xc00036a030}, 0xc000670360, 0x0)
        pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001308c0, {0x1cf5d50, 0xc0003276c0}, 0xc0006d9440, 0xc000595980, 0x232aac0, 0x0)
        pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0001308c0, {0x1cf5d50, 0xc0003276c0}, 0xc0006d9440, 0x0)
        pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-confluent_1.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by linouk23** [comment]
Created a PR to internal repository to fix this issue that should go live in the next release 👌

**Comment by linouk23** [comment]
@andreniklasson we've just released [version](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#190-october-24-2022) `1.9.0` of TF Provider for Confluent that should fix this "panic: reflect: call of reflect.Value.FieldByName on ptr Value"  problem, feel free to reopen if you manage to reproduce the issue.

**Comment by andreniklasson** [comment]
@linouk23 Perfect ,thanks so much for such a quick fix!
@nick-osborn Thanks for providing your your config! I got it to work, but I did not have to add the broker details
