### ISSUE TITLE
Feature request: IAM Invitations

### ISSUE THREAD

**Issue by sawyerw-mastery** [confluentinc/terraform-provider-confluent#133]
I was wondering if there could be support in Terraform for sending IAM invitations. It looks like the ccloud-sdk-go-v2 supports the API endpoints:

https://github.com/confluentinc/ccloud-sdk-go-v2/tree/master/iam/v2#documentation-for-api-endpoints

We currently manage all of our AD through Terraform so it would make it that much easier to invite folks to Confluent.

**Comment by linouk23** [comment]
cc @sawyerw-mastery @Christian-Schmid

We've just released a new version of TF Provider for Confluent that includes new confluent_invitation [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_invitation) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_invitation) in a [Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy).

Let me know if that helps with this issue!

**Comment by linouk23** [comment]
cc @sawyerw-mastery @Christian-Schmid

We've got a quick question: will it be helpful if we rename `confluent_invitation` to `confluent_user` (that leverages both [Invitations API](https://docs.confluent.io/cloud/current/api.html#tag/Invitations-(iamv2)) and [Users API](https://docs.confluent.io/cloud/current/api.html#tag/Users-(iamv2))) and allow you folks to manage users via TF instead of having a bunch of accepted `confluent_invitation` resources that might be tricky to delete (AFAIK a user gets 400 when they try to call `Delete an Invitation` when the invitation is already accepted)?

**Comment by linouk23** [comment]
Update: we released new `confluent_invitation` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_invitation) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_invitation) in a [Generally Available lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy) (https://github.com/confluentinc/terraform-provider-confluent/issues/133).

Regarding

> https://github.com/confluentinc/terraform-provider-confluent/issues/133#issuecomment-1460807604

Ultimately the decision was made to have TF resource match API resource to have the same UX across all clients.

**Comment by linouk23** [comment]
fyi @Christian-Schmid @sawyerw-mastery
