### ISSUE TITLE
data.confluent_kafka_cluster Endpoint

### ISSUE THREAD

**Issue by pixie79** [confluentinc/terraform-provider-confluent#153]
Hi,

It looks like the data resource for confluent_kafka_cluster is not using the endpoint set in the providers override.

```
provider "confluent" {
  cloud_api_key       = var.confluent_cloud_api_key
  cloud_api_secret    = var.confluent_cloud_api_secret
  kafka_rest_endpoint = var.kafka_rest_endpoint
  kafka_api_key       = data.aws_ssm_parameter.cluster_api_key_name.value
  kafka_api_secret    = data.aws_ssm_parameter.cluster_api_key_secret.value
}
```

```
data "confluent_kafka_cluster" "this" {
  id = var.confluent_cluster_id
  environment {
    id = var.confluent_environment_id
  }
}
```

I then get the following timeout error.

```
data.confluent_kafka_cluster.this: Still reading... [1m0s elapsed]
╷
│ Error: error reading Kafka Cluster "lkc-XXXXX": Get "https://api.confluent.cloud/cmk/v2/clusters/lkc-XXXXX?environment=env-XXXXX": GET https://api.confluent.cloud/cmk/v2/clusters/lkc-XXXXX?environment=env-XXXXX giving up after 5 attempt(s): Get "https://api.confluent.cloud/cmk/v2/clusters/lkc-XXXXX?environment=env-XXXXX": net/http: TLS handshake timeout
│ 
│   with data.confluent_kafka_cluster.this,
│   on data.tf line 1, in data "confluent_kafka_cluster" "this":
│    1: data "confluent_kafka_cluster" "this" {
│ 
╵
Error: Process completed with exit code 1.
```

Looking at the url api.confluent.cloud that would not be what I have for the var.kafka_rest_endpoint ?
Should this not use the endpoint url as the cluster has no internet access nor does the location running terraform.

Thanks

**Comment by linouk23** [comment]
Thanks for creating an issue @pixie79!

```
net/http: TLS handshake timeout
```
looks a little bit unexpected for sure.

Thanks for sharing an example config, I'll try to reproduce it locally.

**Comment by linouk23** [comment]
Thanks for waiting @pixie79!

I copied your TF configuration but I didn't manage to reproduce the issue:
```
terraform {
  required_providers {
    confluent = {
      source  = "confluentinc/confluent"
      version = "1.23.0"
    }
  }
}

provider "confluent" {
  cloud_api_key    = var.confluent_cloud_api_key
  cloud_api_secret = var.confluent_cloud_api_secret
  kafka_rest_endpoint = "https://pkc-....us-west-2.aws.confluent.cloud:443"
  kafka_api_key       = "ARWEQEZAGSFJJXV2"
  kafka_api_secret    = "..."
}

data "confluent_kafka_cluster" "this" {
  id = "lkc-..."
  environment {
    id = "env-9k5g1v"
  }
}

output "cluster" {
  value = data.confluent_kafka_cluster.this
}
```

```
$ terraform apply
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

cluster = {
  "api_version" = "cmk/v2"
  "availability" = "SINGLE_ZONE"
  "basic" = tolist([
    {},
  ])
  "bootstrap_endpoint" = "SASL_SSL://pkc-....us-west-2.aws.confluent.cloud:9092"
  "cloud" = "AWS"
  "dedicated" = tolist([])
  "display_name" = "cluster_0"
  ...
  "region" = "us-west-2"
  "rest_endpoint" = "https://pkc-....us-west-2.aws.confluent.cloud:443"
  "standard" = tolist([])
}
```

**Comment by linouk23** [comment]
Could you double check your firewall settings or something?

It might be also helpful to share debug logs:
```
➜  $ export TF_LOG=trace                                                                                        
➜  $ export TF_LOG_PATH="./logs.txt"
```

and then you might look at `logs.txt` for a more descriptive error message / feel free to send it to `cflt-tf-access@confluent.io` after removing all the sensitive data.

**Comment by pixie79** [comment]
Firewall was shut blocking access to the internet. The only route available was via the private twg link to the cluster.

**Comment by linouk23** [comment]
@pixie79 it sounds like you found the issue 👍 (TF Provider needs access to `https://api.confluent.cloud/*` to function properly + Kafka Cluster's REST Endpoints like `https://pkc-aaaaa.us-east-2.aws.confluent.cloud:443`), shall we resolve the issue?

**Comment by pixie79** [comment]
Um no

I would not say this is closed and more a design floor. If I am using this to control a private cluster off network then I should be able to do so without contacting api.confluent. The entire api should be available via an internal only route. At this point all the other resources are only available via the internal connection and private runners are needed to talk to the cluster why would I want a security hole to open a connection to the main api.

**Comment by linouk23** [comment]
> The entire api should be available via an internal only route.

Sure, let me give you more context about it, seems like there's a little bit of a misunderstanding @pixie79.

If we zoom out, most of the resources map to corresponding API Resources that map to API endpoints / routes on `https://api.confluent.cloud/*` (so called "control plane"). These API endpoints is available publicly from anywhere by design. For example, `confluent_service_account` maps to `https://api.confluent.cloud/iam/v2/service-accounts` [API Endpoint](https://docs.confluent.io/cloud/current/api.html#tag/Service-Accounts-(iamv2)/operation/createIamV2ServiceAccount).

Then there're other resources like Topic / ACLs that don't need to talk to `https://api.confluent.cloud/*` (so called "data plane" resources).

That said, if your Terraform configuration only has Kafka resources (like Topic) and don't need to talk to `https://api.confluent.cloud/*` you might be able to get away with no having `https://api.confluent.cloud/*` in your firewall rules. In this case, you might want to get rid of `data "confluent_kafka_cluster" "this" {` to make it work. (that said, there's a temporary workaround for `confluent_kafka_acl` resource that calls `https://api.confluent.cloud/*` anyway).

> The entire api should be available via an internal only route.

You might be talking about Kafka REST Endpoint here which is available internally for private dedicated clusters. Unfortunately, Kafka REST Endpoint only hosts ACL / Topic endpoints so you could only manage ACL / Topic resources via this endpoint and you'll still need `https://api.confluent.cloud/*` to manage other resources.

Let me know if that makes sense.
