### ISSUE TITLE
confluent_schema and confluent_schema_registry_cluster should support compatibility mode configuration

### ISSUE THREAD

**Issue by serhiimakogon** [confluentinc/terraform-provider-confluent#155]
Currently [confluent_schema](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema) and [confluent_schema_registry_cluster](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema_registry_cluster) resources don't support compatibility mode configuration. It would be nice to have that option.

**Comment by linouk23** [comment]
Thanks for creating an issue!

By the way, do you think it's a better idea to have a new `compatibility_mode` attribute for [confluent_schema](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema) and [confluent_schema_registry_cluster](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema_registry_cluster) resources or have new `confluent_schema_config` / `confluent_subject_config` / `confluent_schema_registry_cluster_config` resources with (for now) `compatibility_mode` attribute (similar to `confluent_kafka_cluster_config`?

**Comment by S1M0NM** [comment]
I think a `confluent_schema_registry_cluster_config` resource could make sense since the `confluent_schema_registry_cluster` seems to be a resource that could require more configuration options in the future while a schema does not.

For the `confluent_schema` resource i think its currently enough to add an attribute to the `confluent_schema` resource since i cannot imagine another config for a schema that would require a own `confluent_schema_config` resource

**Comment by linouk23** [comment]
What about `confluent_subject_config`? I'm not sure TF Provider will ever support `confluent_subject` because of API limitations.

**Comment by S1M0NM** [comment]
You could also add a `confluent_subject_config` resource.

But i'm not sure if its reasonable since you could simply put the `compatibility_mode` inside the `confluent_schema` resource or a the `confluent_schema_config` resource. 
Could be confusing if you got a config for something you cannot create as a own resource since the subject is created using the `confluent_schema` resource. So why not configure it for the schema?

**Comment by linouk23** [comment]
Thanks for the comment!

Actually when I took another look at docs I could find the following:
* [mode](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#mode) (on a cluster and a subject level) -- e.g., `IMPORT`, `READONLY`, `READWRITE`.
* [compatibility_level](https://docs.confluent.io/platform/current/schema-registry/develop/api.html#mode) (on a cluster, on a subject level) -- e.g., `BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE`.

**Comment by S1M0NM** [comment]
After having a look into the linked docs and the api reference i think it makes sense to provide the `confluent_subject_config` and `confluent_schema_registry_cluster` resources to be able to configure the `mode` and `compatibility_level`

**Comment by linouk23** [comment]
OK I started working on it and the final implementation will probably deviate a little bit from the initial suggestion we discussed. Most likely, we'll have 4 resources:

* `confluent_subject_mode`
* `confluent_subject_compatibility_level`
* `confluent_schema_registry_cluster_mode`
* `confluent_schema_registry_compatibility_level`

The reason is `mode` and `compatibility_level` API resources have separate API endpoints and we'd like to keep 1:1 relationship between TF and API resources -- otherwise we might run into edge cases like `UPDATE mode` request went through but `UPDATE compatibility_level` so the change could be applied partially which is something we'd like to avoid.

**Comment by linouk23** [comment]
👋 @serhiimakogon @S1M0NM, we've just 

* Added new `confluent_subject_mode` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_subject_mode) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_subject_mode) in an [Open Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy) ([#155](https://github.com/confluentinc/terraform-provider-confluent/issues/155)).
* Added new `confluent_subject_config` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_subject_config) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_subject_config) in an [Open Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy).
* Added new `confluent_schema_registry_cluster_mode` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema_registry_cluster_mode) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_schema_registry_cluster_mode) in an [Open Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy) ([#155](https://github.com/confluentinc/terraform-provider-confluent/issues/155)).
* Added new `confluent_schema_registry_cluster_config` [resource](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_schema_registry_cluster_config) and a corresponding [data source](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/data-sources/confluent_schema_registry_cluster_config) in an [Open Preview lifecycle stage](https://docs.confluent.io/cloud/current/api.html#section/Versioning/API-Lifecycle-Policy).

in [1.24.0](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#1240-january-5-2023) version of TF Provider.
