### ISSUE TITLE
Slow Performance (v0.7.0) : Creating an admin account, topic with Producer/Consumer

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/terraform-provider-confluent#24]
Firstly, well done on adding all the new features to 0.7.0 release. 

Now to the issue
-----
When I use the 0.7.0 version to provision (nothing more than what is being done in the sample examples)
(1) an admin account with CloudClusterAdmin RBAC
(2) A single topic with producer and consumer account with respective ACL's

**it's takes > 6 to 8 mins to have all the resources provisioned**.  Using the CLI directly, something like this would take a few seconds (20 to 30 seconds) to provision the same resources. 

Below are some of the output logs indicating how long the steps take 

rbac binding flow
```
confluent_role_binding.app-manager-kafka-cluster-admin: Creating...
confluent_role_binding.app-manager-kafka-cluster-admin: Still creating... [10s elapsed]
...............
confluent_role_binding.app-manager-kafka-cluster-admin: Still creating... [3m0s elapsed]
```

api-key generation  (every key generating resource seems to be take 2 mins on average)
```
confluent_api_key.app-manager-kafka-api-key: Still creating... [10s elapsed]
confluent_api_key.app-manager-kafka-api-key: Still creating... [20s elapsed]
...............
confluent_api_key.app-manager-kafka-api-key: Still creating... [2m0s elapsed]

```

I am wondering the impact of the slow performance when we have to scale the kafka resource provisioning on our end using terraform.  Is this something your team is aware of - the performance implications when using the terraform provisioning and any plans to improve the provisioning time?  

Thanks.

**Comment by linouk23** [comment]
👋 @bluedog13, thanks for reporting an issue!

> Firstly, well done on adding all the new features to 0.7.0 release.
👏 

> it's takes > 6 to 8 mins to have all the resources provisioned. Using the CLI directly, something like this would take a few seconds (20 to 30 seconds) to provision the same resources.

You've identified all the issues correctly: `confluent_api_key` and `confluent_role_binding` are the "slowest" resources to provision (after networking resources / clusters).

The gotcha here is we made a design decision that TF Provider should ensure that the target resource is not only created but it's also ready to use (unfortunately it takes a little bit of time for a Kafka API Key to sync with a Kafka cluster and, similarly, for a role binding to be applied) for a better user experience (otherwise a user might see a random error in the middle of `terraform apply` and will have to rerun `terraform apply` command).

The idea here is we expect the majority of users to run TF not locally but using CI or something so having to wait for 10 minutes more is a better UX than having to rerun a job on CI.

That said, we acknowledge TF Provider is a bit too slow right now and we're looking at ways to make it work faster. More specifically,

* `confluent_api_key`: (Cloud API Key's provisioning time is pretty fast so I assume it's about Kafka API Key) because of some internal details it's a little bit tricky to figure out whether Kafka API Key is ready to use so TF Provider [waits](https://github.com/confluentinc/terraform-provider-confluent/blob/v0.7.1/internal/provider/utils_wait.go#L26-L47) for an extra minute before finishing the provisioning process. Our backend team is actively trying to speed it up from their side though.

* `confluent_role_binding`: TF Provider is playing safe here and basically [waits](https://github.com/confluentinc/terraform-provider-confluent/blob/v0.7.1/internal/provider/resource_role_binding.go#L99) for 3 minutes after it sends `POST` request. I think it's possible to reduce this time to 1 minute or something, or, even better, implement a retry for `403` (that a user will see when a role binding wasn't applied & synced) on `CREATE` operations for downstream resources that are trying to leverage this role binding. We're working to ship this improvement in one of our next releases 👌 

Thanks for asking such a great question and I'll keep this issue open until we ship an improvement that will speed up the provisioning time for `confluent_role_binding` resource at least.

**Comment by bluedog13** [comment]
Thank you for the reply and the reasoning behind the design.

**Comment by bluedog13** [comment]
When setting RBAC roles for 10 users (DeveloperRead) with access to topic and consumer group,  it's 10*2*3 = 60 minutes. 

In scenarios where we plan to bulk assign roles to an entire team - it could take a whole lot of time.

**Comment by linouk23** [comment]
@bluedog13 

update: we're going to speed up role binding creation by 7.5x in our next release: instead of waiting for 3 minutes we'll wait for just 40 seconds.

**Comment by linouk23** [comment]
@bluedog13 we're happy to let you know we've just released `0.9.0` [version](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md#090-may-25-2022) of TF Provider that decreased the creation time of `confluent_role_binding` resource by 4.5x.

**Comment by swapsCAPS** [comment]
We are hitting this as well. API keys take a long time to provision due to the "wait" time. 
Is it possible to opt out of this behavior? 
In the end we only need the secret associated with the API key for downstream resources and don't really care if the API key is not fully synced yet.

**Comment by linouk23** [comment]
@swapsCAPS, could you create a separate issue? It seems like this issue is about role bindings and yours is about API Keys, and I'll reply to you there. Thank you!
