### ISSUE TITLE
Set a Schema to a Topic

### ISSUE THREAD

**Issue by hsmitty93** [confluentinc/terraform-provider-confluent#257]
Hello, I'm wondering if there's a way to set a schema to a topic in the provider. We're creating schemas and topics in terraform but I have yet to find any examples or docs on how to link the two together. Currently we're setting them via Confluent Cloud console.  

Confluent Cloud Ref: 
- [Create a topic schema](https://docs.confluent.io/cloud/current/sr/schemas-manage.html#create-a-topic-schema)

**Comment by linouk23** [comment]
👋 thanks for asking @hsmitty93!

See 

* https://docs.confluent.io/platform/current/schema-registry/fundamentals/serdes-develop/index.html#how-the-naming-strategies-work
* https://developer.confluent.io/learn-kafka/schema-registry/schema-subjects/#topicnamestrategy

You might want to take a look at
* [single-event-types-avro-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/single-event-types-avro-schema)
* [multiple-event-types-proto-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/multiple-event-types-proto-schema)
* [multiple-event-types-avro-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/multiple-event-types-avro-schema)
* [single-event-types-proto-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/single-event-types-proto-schema)

which are all create schemas that attach to a topic because of the naming strategy they’re using.

For example, here's a [code pointer](https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/single-event-types-avro-schema/main.tf#L268) where "purchase-value" is `${topic-name}-value`.

![image](https://github.com/confluentinc/terraform-provider-confluent/assets/5459870/98469651-147d-4810-9732-417811a04c19)
![image](https://github.com/confluentinc/terraform-provider-confluent/assets/5459870/6f353cd7-1bf2-4d62-bd4b-1952274065a7)

These screenshots were taken after running [single-event-types-proto-schema](https://github.com/confluentinc/terraform-provider-confluent/tree/master/examples/configurations/single-event-types-proto-schema) in particular.

Let me know if that helps!

**Comment by hsmitty93** [comment]
Ahhh, thank you for pointing this out! I kept looking at these files trying to figure out where the setting is happening, but it looks to be just the convention of adding -value or -key to the topic name you want the schema set to.
