### ISSUE TITLE
confluent_schema Resource import should not require SCHEMA_CONTENT

### ISSUE THREAD

**Issue by Noel-Jones** [confluentinc/terraform-provider-confluent#293]
I am admittedly still learning schemas but I am well versed in Terraform and I have successfully imported all of our clusters and topics into Terraform and I am using Terraform to manage Users, API keys, topics, ACLs. Now I am looking at the schemas. I am really surprised that in order to import a schema I need to specify the schema content via an environment variable. This is completely unlike any other import that I have come across. It should not be necessary and the requirement for the variable should be removed to make the import process simple - the import process should populate the schema information, including the content, from the existing resource.

**Comment by Noel-Jones** [comment]
I just retested this, maybe with a later version but more likely (having spent the morning reading the provider code) without setting SCHEMA_CONTENT. It does indeed perform the import as expected taking the latest schema.

This can therefore be change to a documentation update to state that SCHEMA_CONTENT *may* be set to import a specific schema content overriding the content that would otherwise be taken from the registry.

It escapes me quite why this may be desired. I can only think that it dates back to a time when reading the schema was not possible or not implemented. I would suggest the use of the variable be removed.

**Comment by linouk23** [comment]
@Noel-Jones thanks for waiting! It's been a while since I looked at these files but let me try to answer your great questions!

You're absolutely right, we have updated it in [this commit](https://github.com/confluentinc/terraform-provider-confluent-internal/commit/946ddd1ba2c5162f12814dae191df32ba60a8793).

> It escapes me quite why this may be desired. I can only think that it dates back to a time when reading the schema was not possible or not implemented. I would suggest the use of the variable be removed.

There're 2 gotchas:
* This variable was already introduced in a resources released as Generally Available so any breaking changes are forbidden unless we release a new major version of TF Provider for Confluent (2.x.x).
* Based on our testing, the algorithm for comparing schema diffs is not perfect, it's somewhat easier to default to the local file version.

We've just updated the docs in our internal repo and the doc changes will be live with our next release of TF Provider, thank you!

**Comment by Noel-Jones** [comment]
Hi Kostya, thanks for looking into it. I would note that importing a schema is not a task that would normally be automated. Not sure I'd call it a breaking change but that is your call of course. If you got here via my PR for the refresh fix then the PR will need updating to put that back.
