### ISSUE TITLE
Is it possible to get Kafka `credentials` from `confluent_kafka_cluster`?

### ISSUE THREAD

**Issue by joedborg** [confluentinc/terraform-provider-confluent#330]
https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#credentials

Is it possible to get the needed for https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#credentials from the created `confluent_kafka_cluster`?

E.g.

```hcl
provider "confluent" {
  cloud_api_key    = var.confluent_cloud_api_key
  cloud_api_secret = var.confluent_cloud_api_secret
}

resource "confluent_kafka_cluster" "dev" {
  display_name = "Development"
  availability = "SINGLE_ZONE"
  cloud        = var.provider_cloud
  region       = var.provider_region
  environment {
    id = resource.confluent_environment.dev.id
  }
  basic {}
}

resource "confluent_kafka_topic" "example" {
  topic_name    = "example"
  rest_endpoint = resource.confluent_kafka_cluster.dev.rest_endpoint
  kafka_cluster {
    id = resource.confluent_kafka_cluster.dev.id
  }
  credentials {
    key    = resource.confluent_kafka_cluster.dev.key
    secret = resource.confluent_kafka_cluster.dev.secret
  }
}
```

So that I don't have to create the cluster with on apply, create the key and secret in Confluent Cloud and then add them as variables?

**Comment by linouk23** [comment]
> Is it possible to get the needed for https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#credentials from the created confluent_kafka_cluster?

Thanks for creating this issue!

There's no API Key attribute in `confluent_kafka_cluster` resource.

**Comment by vilmosnagy** [comment]
Hi @linouk23 ,

I’d like to follow up on the issue mentioned in #330.

I am trying to automate the creation of a Kafka cluster and associated topics in Confluent Cloud using Terraform from our CI/CD pipeline. However, I’m facing challenges with the `credentials` block, as I am unable to generate the required values for it using Terraform.

> So that I don't have to create the cluster with on apply, create the key and secret in Confluent Cloud and then add them as variables?

Has this issue been addressed, or are there any workarounds or updates available? It seems that the ability to automatically create both a Kafka cluster and topics within it is currently not feasible due to this limitation.

Any guidance or suggestions would be greatly appreciated. Thank you!

**Comment by linouk23** [comment]
@vilmosnagy thanks for reaching out! Could you check whether using https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#option-2-manage-a-single-kafka-cluster-in-the-same-terraform-workspace resolves the issue?

**Comment by vilmosnagy** [comment]
> Could you check whether using https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_kafka_topic#option-2-manage-a-single-kafka-cluster-in-the-same-terraform-workspace resolves the issue?

I don't think so. Let me explain our use case:

We have a microservices-based stack deployed with Helm charts, mainly running on a Kubernetes cluster. This is managed in a Git repository using a GitOps approach. When a change is introduced, we create a new Git branch that deploys a full stack—including the updated components—on Kubernetes.

In parallel with the helmfile sync, we provision the necessary cloud resources (e.g., databases, DNS entries, S3 buckets) using Terraform. Once the change is merged, we destroy the corresponding Kubernetes namespace and clean up the cloud resources with Terraform.

What I’d like to achieve is provisioning an entirely new Kafka cluster in Confluent Cloud—including topics, API keys, etc.—within a single Terraform run, and without any manual steps.

As far as I understand, the linked solution doesn't support that scenario, because it assumes the Kafka cluster already exists before running the Terraform commands.

**Comment by linouk23** [comment]
@vilmosnagy 

> What I’d like to achieve is provisioning an entirely new Kafka cluster in Confluent Cloud—including topics, API keys, etc.—within a single Terraform run, and without any manual steps.

Gotcha, could you take a look at https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/standard-kafka-acls/main.tf and see whether it helps?
