### ISSUE TITLE
401 While Creating a Connector

### ISSUE THREAD

**Issue by markjbyrne** [confluentinc/terraform-provider-confluent#361]
hey folks, I am encountering a 401 when I attempt to create a postgres sink connector using the terraform provider.  Error below,

```
confluent_connector.postgres_sink_connector: Creating...
╷
│ Error: error creating Connector: error creating Connector: error sending validation request: 401 Unauthorized
│ 
│   with confluent_connector.postgres_sink_connector,
│   on main.tf line 238, in resource "confluent_connector" "postgres_sink_connector":
│  238: resource "confluent_connector" "postgres_sink_connector" {
```

I do not believe this is an issue with the terraform service account as I am able to create all other resources related to creating a connector (service account, ACLs etc.) using it.  

However, I have also tested the database credentials by successfully creating a Postgres sink connector via the console using the same creds.  

Hard coding the database credentials into the main.tf file to eliminate credential retrieval via secrets has also led to the same 401 error.

Can you provide any pointers to what this 401 error is related to to help me narrow down the cause.

**Comment by markjbyrne** [comment]
seeing a 401 when trying to create role bindings also

**Comment by markjbyrne** [comment]
I have solved this issue.  It was due to the service account being created with a reference to a specific provider alias.

**Comment by markfickett** [comment]
I ran into this error message creating a confluent connector (for MySqlCdcSourceV2) using the Pulumi provider that wraps this Terraform provider. Describing the solution here since it's a top result for this error message.

I needed to provide the API key that the Pulumi/Terraform connector provider uses to interact with Confluent Cloud's APIs. Without it, before Confluent is even trying to create your resources or talking to you yet, you run into this 401 error. But there's no error up front if the API key is simply missing / not set, API calls against Confluent just fail unauthorized. I set it via env vars, using keys for a service account dedicated for IaC usage that has org admin permissions:

```sh
export CONFLUENT_CLOUD_API_KEY=''
export CONFLUENT_CLOUD_API_SECRET=''
```

Within your Confluent resources, there's a separate API key that Confluent uses internally to actually create the resource. I used IaC-generated API keys that have admin permissions on one cluster/env. So you will likely also specify:

```py
"kafka.auth.mode": "KAFKA_API_KEY",
"kafka.api.key": "my_kafka_cluster_admin_apikey_id",
"kafka.api.secret": "my_kafka_cluster_admin_apikey_secret",
```

Potentially some of this info would be very useful either in a presence check for API creds or more details when a 401 response is detected [at the connector resource API call](https://github.com/confluentinc/terraform-provider-confluent/blob/67232c99b4509dd1e590b162cf1515ae595439f6/internal/provider/resource_connector.go#L236) site.
