### ISSUE TITLE
Cannot import API KEYs

### ISSUE THREAD

**Issue by isatfg** [confluentinc/terraform-provider-confluent#433]
I have tried to import and api_key using the example

```
$ export CONFLUENT_CLOUD_API_KEY="<cloud_api_key>"
$ export CONFLUENT_CLOUD_API_SECRET="<cloud_api_secret>"
$ export API_KEY_SECRET="<api_key_secret>"

# Option #1: Cluster API Key
$ terraform import confluent_api_key.example_kafka_api_key "env-abc123/UTT6WDRXX7FHD2GV"
```

However I keep getting the error
`401 Unauthorized: invalid API key: make sure you're using a Cloud API 
`

Not sure what I'm doing wrong.  My CONFLUENT_CLOUD_API_KEY was create with the resource scope Cloud Resource Management.
The API_KEY_SECRET was create in the environment -->cluster -->API Keys

**Comment by cqin-confluent** [comment]
:wave: @isatfg, thank you for creating this issue!

"invalid API key: make sure you're using a Cloud API" implies that there could be a typo in 
$ export CONFLUENT_CLOUD_API_KEY="<cloud_api_key>"
$ export CONFLUENT_CLOUD_API_SECRET="<cloud_api_secret>"

where you might be using Kafka / SR API Key instead of a Cloud API Key. Could you double check that you use Cloud API Key (via CLI / UI)? Thank you!

**Comment by isatfg** [comment]
I think there was an environment variable set which was causing my issue. I started a new terminal and it worked as expected
