### ISSUE TITLE
version numbers should not be put against resource names

### ISSUE THREAD

**Issue by Marcus-James-Adams** [confluentinc/terraform-provider-confluent#55]
I see that the latest update has started putting version numbers against resource names

Could somebody explain the reasoning behind this?

Putting version numbers means that existing codes and existing state files will break every time a resource name is changed and that customers will have to re-import potentially 100's, 1,000s of items ( when you get to production services), now this is just about ok whilst code is a public preview - except it will effect those testing in dev environments but one it's gone live it becomes a deal-breaking for enterprise customers

version numbers should be set at the provider level.

**Comment by linouk23** [comment]
@Marcus-James-Adams our upcoming `0.12.0` release will revert resource versioning changes introduced in `0.11.0`. User feedback on versioned resources made it clear that the pain of manually updating the TF state file outweighs the potential benefits of deprecation flexibility that versioned resources could have provided. In order to avoid forcing users to edit their TF state files (either manually or by running commands like `terraform state mv`) in the future, TF [state migrations](https://www.terraform.io/plugin/sdkv2/resources/state-migration) will be handled within the Confluent Terraform Provider whenever possible.

**Comment by linouk23** [comment]
@Marcus-James-Adams find our latest `0.12.0` [release](https://registry.terraform.io/providers/confluentinc/confluent/0.12.0).

**Comment by lra** [comment]
Oh god... I spent hours migrating all our resources to match 0.11, and now you are rolling back and I have to spend hours on this again?!

Let's please be careful next time...

**Comment by linouk23** [comment]
@lra that is very unfortunate to hear. On a happy note, this is a one-off

> In order to avoid forcing users to edit their TF state files (either manually or by running commands like `terraform state mv`) in the future, TF [state migrations](https://www.terraform.io/plugin/sdkv2/resources/state-migration) will be handled within the Confluent Terraform Provider whenever possible.

and going forward, we expect all changes to TF state to handle automatically 🤞

**Comment by ConfluentSpencer** [comment]
I'm sorry @lra! We understand this is a pain. We made an incorrect optimization and have now reverted it. We will try our best to avoid these painful migrations going forward.

**Comment by lra** [comment]
I understand that it's for the best, I just had to vent I guess =(
Thanks for your work on the provider!
