### ISSUE TITLE
upgrading to 0.11.0 from >= 0.7.0

### ISSUE THREAD

**Issue by filippo-qmee** [confluentinc/terraform-provider-confluent#77]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/101411026/182175661-8e4a79f1-91f3-4567-bdf2-f8897f5cfeae.png">

I want to migrate to 0.11.0 but I am a bit confused by the docs: https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.11.0.

Can I migrate from 0.7.0 to 0.11.0 since the documentation links me to the [Confluent Provider 0.7.0: Upgrade Guide](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.7.0) ?

**Comment by linouk23** [comment]
Thanks for asking @filippo-qmee!

That's a great catch and looks like a typo that we might want to fix!

The idea here is there're naming changes in `0.11.0` that we reverted in `0.12.0` so that's long winded way to allow users to skip that version if possible.

We'd recommend the following:

1. Update a version from `0.7.0` to `0.10.0` in your TF configuration -- most likely, you won't need to update resource definitions.
2. Follow [this doc](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.12.0#upgrade-guide-upgrading-from-version-0100-of-confluent-provider) to update `0.10.0` -> `0.12.0`
3. Update a version from `0.12.0` to `1.0.0` in your TF configuration -- you won't need to update resource definitions.

Let me know if that helps!
