### ISSUE TITLE
add rbac_crn ouput in confluent_kafka_topic  resource

### ISSUE THREAD

**Issue by javiervelamindcurv** [confluentinc/terraform-provider-confluent#87]
add rbac_crn ouput in confluent_kafka_topic  resource

**Comment by linouk23** [comment]
Thanks for opening an issue!

For now you could [use](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/resources/confluent_role_binding) something like
```
resource "confluent_role_binding" "topic-example-rb" {
  principal   = "User:${confluent_service_account.test.id}"
  role_name   = "DeveloperWrite"
  crn_pattern = "${confluent_kafka_cluster.basic.rbac_crn}/kafka=${confluent_kafka_cluster.standard.id}/topic=${confluent_kafka_topic.orders.topic_name}"
}
```

Do you think have a new computed `resource_name` attribute might be useful?

**Comment by javiervelamindcurv** [comment]
I know you can build your own crn_pattern I think it could be more easy:

```
resource "confluent_kafka_topic" "orders" {
  kafka_cluster {
    id = confluent_kafka_cluster.basic-cluster.id
  }
  topic_name         = "orders"
  partitions_count   = 4
  rest_endpoint      = confluent_kafka_cluster.basic-cluster.rest_endpoint
  credentials {
    key    = confluent_api_key.app-manager-kafka-api-key.id
    secret = confluent_api_key.app-manager-kafka-api-key.secret
  }
}

resource "confluent_role_binding" "topic-example-rb" {
  principal   = "User:${confluent_service_account.test.id}"
  role_name   = "DeveloperWrite"
  crn_pattern = confluent_kafka_topic.orders.rbac_crn
}
```

PD: cluster resource export the attribute rbac_crn, why doesn't topic expose the attribute? :)

**Comment by linouk23** [comment]
That's a great question @javiervelamindcurv!

The reason is it's an API limitation in some sense. If you closely look at cluster / topic resource definitions you'll see that even though `confluent_kafka_cluster` includes `environment { id }`, `confluent_kafka_topic` doesn't use `environment { id }`. The reason is `GET cluster/id/` endpoint needs `environmentID` whereas for topics we use a completely different API and `GET topic/id/` doesn't need `environment { id }`.

As a result, we can't really construct `rbac_crn` a topic since it should contain `environment { id }` which is effectively unknown at a topic resource level.

Let me know whether it makes sense!
