### ISSUE TITLE
Resource "azurerm_private_dns_a_record" "zonal" = for_each value depends on resource attributes

### ISSUE THREAD

**Issue by rogerioefonseca** [confluentinc/terraform-provider-confluent#96]
## Description:
When I'm trying to create the resource `"azurerm_private_dns_a_record" "zonal"`, I'm getting the error below.

│ The "for_each" value depends on resource attributes that cannot be
│ determined until apply, so Terraform cannot predict how many instances will
│ be created. To work around this, use the -target argument to first apply
│ only the resources that the for_each depends on.

## Steps to Reproduce

resource "azurerm_private_dns_a_record" "zonal" {
  for_each = confluent_network_v1.network.azure[0].private_link_service_aliases

  name                = "*.az${each.key}"
  zone_name           = azurerm_private_dns_zone.hz.name
  resource_group_name = var.resource_group_name
  ttl                 = 60
  records = [
    azurerm_private_endpoint.endpoint[each.key].private_service_connection[0].private_ip_address,
  ]

  depends_on = [ confluent_network_v1.network ]
}

I read the documentation, but I did not have a clue how to work around that.

I'm using your [example ](https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/dedicated-privatelink-azure-kafka-acls/main.tf#L352) as a reference, and I would like to know how did you work that around?

The only solution that |I found so far was to, before creating the cluster apply the network manually like:
`tf apply -target module.confluentcloud_kafka_cluster.confluent_network_v1.network`

**Comment by linouk23** [comment]
@rogerioefonseca thanks for creating this issue!

> When I'm trying to create the resource "azurerm_private_dns_a_record" "zonal", I'm getting the error below.

Right, that's what we run into as well which is why we included the following note to the [README](https://github.com/confluentinc/terraform-provider-confluent/blob/master/examples/configurations/dedicated-privatelink-azure-kafka-acls/README.md) of that example: 
![image](https://user-images.githubusercontent.com/5459870/188489197-d36ba37a-8bbd-4021-9af4-2109b33e5678.png)

which is exactly the same workaround you found.

Let me know whether it helps.
